// Beauty salon spec study — drives /beauty-salons page content.
// Every capability claim cites the research fact sheet:
//   aios-starter-kit/reference/website-api-research/beauty-salons.md

import type { SpecStudy } from './home-services'

export const beautySalonsSpec: SpecStudy = {
  intro:
    'Prestique builds AI voice and text agents for beauty salons on top of the booking system already running the front desk, so the chair stays full while your stylists keep working.',

  problem: [
    "Your stylists can't answer the phone with foils in or scissors in hand, and the front desk is checking someone out. In Zenoti's call data, 37% of salon calls go unanswered and 82% of those misses happen during business hours, not after close. Fewer than 1 in 4 callers who hit voicemail leave a message. The rest book somewhere that picked up.",
    "Clients feel it. In a 2025 Zenoti survey of more than 1,000 US salon and spa-goers, 71% said they had decided not to book because it was too hard to reach someone or book online, and 48% said they would be much more likely to return to a salon that let them book or change an appointment any time.",
    "The bigger leak is the rebook. The average salon rebooks about 10% of clients within 24 hours of a visit; top earners rebook around 30%. Every client who leaves without the next root touch-up or trim on the calendar is a visit you have to win back later. Missed-call texting and your booking app's built-in chatbot answer the easy questions. They don't chase the rebook, fill tomorrow's cancellation from the waitlist, or collect a deposit from the client who no-showed twice.",
  ],

  stack: [
    {
      tool: 'Square Appointments',
      role: 'Booking and POS — self-serve Bookings API',
      capabilities: [
        'OAuth 2.0 with appointment read/write scopes and a full sandbox environment',
        'Create, update and cancel bookings; search availability by service, team member and location',
        'booking.created and booking.updated webhooks keep the agent in sync with the calendar',
        'Calendar writes require the Appointments Plus or Premium plan; we check this before the build starts',
      ],
      docUrl: 'https://developer.squareup.com/docs/bookings-api/what-it-is',
    },
    {
      tool: 'Zenoti',
      role: 'Salon and spa management — documented booking API',
      capabilities: [
        'API key generated by the business in its own Zenoti settings, no partner approval wait',
        'Full booking flow: find slots, reserve, confirm, reschedule and cancel',
        'Single-stylist bookings keep a colour and a cut together on one provider',
        'Webhooks for bookings, no-shows, completed appointments and SMS opt-in/opt-out',
      ],
      docUrl: 'https://docs.zenoti.com/docs/service-booking-apis.md',
    },
    {
      tool: 'Phorest',
      role: 'Salon management — third-party API on request',
      capabilities: [
        'Check availability across services and date ranges, then create, confirm and cancel bookings',
        'Deposit payment links calculated from the branch’s own deposit settings',
        'Client search by phone or email with full service history for rebooking',
        'Access requested through Phorest Support; no webhooks, so the agent polls for changes',
      ],
      docUrl: 'https://developer.phorest.com/docs/getting-started.md',
    },
    {
      tool: 'Meevo',
      role: 'Salon and spa management — partner API',
      capabilities: [
        'Read, create, update and delete appointments, clients, employees and gift cards',
        'Separate test environment before production credentials are issued',
        'Access by request form; 1,000 calls per location per day included',
      ],
      docUrl: 'https://docs.meevoapi.com/',
    },
    {
      tool: 'Mindbody / Booker',
      role: 'Salon, spa and wellness management — Public API v6',
      capabilities: [
        'Bookable-item search for open slots, then appointment creation',
        'Activated per salon: the owner enters a site-specific activation code',
        'Sandbox site for development before touching your live schedule',
      ],
      docUrl: 'https://developers.mindbodyonline.com/PublicDocumentation/V6',
    },
    {
      tool: 'Vagaro',
      role: 'Salon booking and payments — API and webhooks on request',
      capabilities: [
        'Availability search by service, stylist and date; appointment and client lookups',
        'Webhooks for appointments, customers, transactions and intake-form responses',
        'Requires Vagaro card processing; the public API does not document booking creation, so the agent hands the chosen slot to your team or your booking link',
      ],
      docUrl: 'https://docs.vagaro.com/public/reference/api-introduction',
    },
    {
      tool: 'VAPI + Twilio',
      role: 'Voice agent and two-way SMS',
      capabilities: [
        'VAPI voice agent on your existing number, with Anthropic Claude as the model',
        'Custom tools look up the client, their stylist and open slots mid-call',
        'Twilio two-way SMS for confirmations, rebooking offers, waitlist fills and deposit links',
        'Call status events flag every unanswered call so nothing drops silently',
      ],
      docUrl: 'https://docs.vapi.ai/tools/custom-tools',
    },
  ],

  agentBehaviors: [
    {
      title: 'Answers the chair-side call',
      description:
        "When a stylist can't pick up, the agent answers, recognises returning clients by phone number, and books the right service with the right stylist, leaving time for a three-hour colour, not a trim-length gap.",
      toolsInvolved: ['VAPI', 'Square', 'Zenoti', 'Phorest', 'Meevo', 'Mindbody'],
    },
    {
      title: 'Rebooks at the interval you set',
      description:
        'You set the interval per service (root touch-up at 6 weeks, trim at 8). The agent reads each client’s last visit and texts the next appointment before they drift, with open times already offered.',
      toolsInvolved: ['Twilio', 'Zenoti', 'Phorest', 'Square'],
    },
    {
      title: 'Fills cancellations from a waitlist',
      description:
        'When a booking cancels, the agent texts clients who asked for an earlier slot with that stylist and books the first one who says yes. No booking platform exposes a waitlist API, so we run the waitlist ourselves.',
      toolsInvolved: ['Twilio', 'Square', 'Zenoti', 'Phorest'],
    },
    {
      title: 'Confirmations and no-show deposits',
      description:
        'The agent confirms tomorrow’s book by text, and for clients with a no-show history or long colour services it sends a deposit link based on your policy before the slot is held.',
      toolsInvolved: ['Twilio', 'Phorest', 'Zenoti'],
    },
    {
      title: 'New-client consultation intake',
      description:
        'Before a first colour appointment, the agent collects hair history, previous colour and box-dye use, and the look they want. It reminds them about your patch-test policy and never quotes a colour price your stylist hasn’t seen.',
      toolsInvolved: ['VAPI', 'Twilio', 'Vagaro'],
    },
    {
      title: 'Review requests after the visit',
      description:
        'When an appointment completes, the agent sends a short check-in and invites happy clients to leave a Google review. Anyone less than happy goes to you instead.',
      toolsInvolved: ['Twilio', 'Zenoti', 'Vagaro'],
    },
  ],

  rollout: [
    {
      week: 1,
      title: 'Discovery and booking-system access',
      tasks: [
        'Map call volume, busy hours, services and durations, stylist rules, and your deposit and cancellation policy',
        'Connect your booking system: Square and Zenoti in days; Phorest, Meevo, Mindbody and Vagaro access requests start the same day',
        'Start A2P 10DLC SMS registration with the carriers, which takes 10 to 15 days',
      ],
      tools: ['Square', 'Zenoti', 'Phorest', 'Twilio'],
      effortHours: '~8-12h',
    },
    {
      week: 2,
      title: 'Voice agent build',
      tasks: [
        'Set up the agent with your services, durations, stylists, hours and the way your front desk talks',
        'Wire live lookups for clients, stylists and open slots into the call',
        'Run it on a test number while your team tries to break it',
      ],
      tools: ['VAPI', 'Twilio'],
      effortHours: '~10-14h',
    },
    {
      week: 3,
      title: 'Text flows and shadow mode',
      tasks: [
        'Turn on confirmations, rebooking offers, waitlist fills and deposit links once SMS registration is approved',
        'Shadow mode: the agent logs what it would have booked so you can check it before it goes live',
        'Set up the alert your team gets whenever a client asks for a person',
      ],
      tools: ['Twilio', 'VAPI'],
      effortHours: '~8-10h',
    },
    {
      week: 4,
      title: 'Go live and tune',
      tasks: [
        'Put the agent on the line for missed and after-hours calls, with a transfer to the front desk always available',
        'Review the first week of calls and texts with you and adjust tone, rules and rebooking intervals',
      ],
      tools: ['VAPI', 'Twilio'],
      effortHours: '~6-10h',
    },
  ],

  impact: [
    {
      label: 'Calls going unanswered',
      before: '~37%',
      after: 'Every call answered',
      source: 'Zenoti call data (before); Twilio call status reporting (after)',
    },
    {
      label: 'Clients rebooked within 24 hours',
      before: '~10% average salon',
      after: 'Toward the ~30% top-earner benchmark',
      source: 'Zenoti 2025 Benchmark Report',
    },
    {
      label: 'Cancelled slots refilled',
      before: 'Whoever the front desk has time to call',
      after: 'Waitlist texted within minutes',
      source: 'Booking webhooks + Twilio SMS',
    },
    {
      label: 'Voicemail callers lost',
      before: '3 in 4 never leave a message',
      after: 'Answered and booked live',
      source: 'Zenoti call data',
    },
  ],

  faqs: [
    {
      q: 'Do we have to change booking software?',
      a: 'No. We build on what you already run. Square Appointments and Zenoti connect in days. Phorest, Meevo and Mindbody need an access request, which we start on day one. Vagaro can be connected for lookups and alerts, but its public API does not document booking creation, so on Vagaro the agent offers the slot and your team or booking link confirms it.',
    },
    {
      q: 'My booking software already has an AI receptionist. Why add this?',
      a: 'Built-in receptionists answer the phone. We build the whole flow around your rules: rebooking at your intervals, filling cancellations from a waitlist, deposit links for repeat no-shows, and one agent that works across calls and texts. If your built-in tool already covers what you need, we will tell you.',
    },
    {
      q: 'Will it quote prices?',
      a: 'Only the prices you give it, for services with fixed prices. Colour and corrective work are booked as consultations, because the price depends on what your stylist sees in the chair.',
    },
    {
      q: 'Can it book the right stylist and the right amount of time?',
      a: 'Yes. It reads your services, durations and stylist rules, so a balayage books a long slot with a colourist and a trim books a short one. Where the platform supports it, multi-service visits stay with one stylist.',
    },
    {
      q: 'Is texting clients compliant?',
      a: 'Every business number is registered for A2P 10DLC before it sends, which takes 10 to 15 days. Appointment texts go to clients who booked with you; marketing texts only go to clients who opted in, and every text honours STOP.',
    },
    {
      q: 'Will clients know it’s AI?',
      a: 'Yes. The agent says it is an assistant for the salon, and a person is always one transfer away. Clients use it more once they know.',
    },
    {
      q: 'How long until it’s live?',
      a: 'About four weeks. The two waits are SMS registration (10 to 15 days) and booking-system access if you are on Phorest, Meevo, Mindbody or Vagaro. We start both in week one.',
    },
  ],
}
